[2025-04-09T22:45:28.420+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T22:45:28.427+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: la_traffic_download_to_bq_via_url.load_csv_to_bigquery scheduled__2025-04-08T00:00:00+00:00 [queued]>
[2025-04-09T22:45:28.431+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: la_traffic_download_to_bq_via_url.load_csv_to_bigquery scheduled__2025-04-08T00:00:00+00:00 [queued]>
[2025-04-09T22:45:28.431+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-09T22:45:28.435+0000] {taskinstance.py:2890} INFO - Executing <Task(GCSToBigQueryOperator): load_csv_to_bigquery> on 2025-04-08 00:00:00+00:00
[2025-04-09T22:45:28.438+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=102) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-09T22:45:28.439+0000] {standard_task_runner.py:72} INFO - Started process 103 to run task
[2025-04-09T22:45:28.440+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'la_traffic_download_to_bq_via_url', 'load_csv_to_bigquery', 'scheduled__2025-04-08T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpu6gpeidz']
[2025-04-09T22:45:28.440+0000] {standard_task_runner.py:105} INFO - Job 49: Subtask load_csv_to_bigquery
[2025-04-09T22:45:28.457+0000] {task_command.py:467} INFO - Running <TaskInstance: la_traffic_download_to_bq_via_url.load_csv_to_bigquery scheduled__2025-04-08T00:00:00+00:00 [running]> on host 6416417ff662
[2025-04-09T22:45:28.487+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='la_traffic_download_to_bq_via_url' AIRFLOW_CTX_TASK_ID='load_csv_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T00:00:00+00:00'
[2025-04-09T22:45:28.488+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-09T22:45:28.488+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-09T22:45:28.488+0000] {logging_mixin.py:190} INFO - Current task name:load_csv_to_bigquery state:running start_date:2025-04-09 22:45:28.427689+00:00
[2025-04-09T22:45:28.488+0000] {logging_mixin.py:190} INFO - Dag name:la_traffic_download_to_bq_via_url and current dag run status:running
[2025-04-09T22:45:28.488+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T22:45:28.489+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-09T22:45:28.489+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud) shall not contain '_' according to RFC3986.
[2025-04-09T22:45:28.489+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-09T22:45:28.490+0000] {gcs_to_bigquery.py:389} INFO - Using existing BigQuery table for storing data...
[2025-04-09T22:45:28.490+0000] {credentials_provider.py:402} INFO - Getting connection using `google.auth.default()` since no explicit credentials are provided.
[2025-04-09T22:45:28.523+0000] {bigquery.py:1315} INFO - Project is not included in destination_project_dataset_table: la_traffic_collision.traffic_collisions; using project "taxi-rides-ny-450705"
[2025-04-09T22:45:28.523+0000] {gcs_to_bigquery.py:393} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'taxi-rides-ny-450705', 'datasetId': 'la_traffic_collision', 'tableId': 'traffic_collisions'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://la-traffic-collision/traffic-collision-data-from-2010-to-present.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2025-04-09T22:45:28.524+0000] {bigquery.py:1241} INFO - Inserting job ***_la_traffic_download_to_bq_via_url_load_csv_to_bigquery_2025_04_08T00_00_00_00_00_21cddda36ddea2f91179dea1feed2a1e
[2025-04-09T22:45:43.011+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 458, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 494907; errors: 1; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 494907; errors: 1; max bad: 0; error percent: 0; reason: invalid, location: gs://la-traffic-collision/traffic-collision-data-from-2010-to-present.csv, message: Error while reading data, error message: Bad character (ASCII 0) encountered.; line_number: 137460 byte_offset_to_start_of_line: 52492230 column_index: 0 column_name: "dr_number" column_type: INT64 value: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000..." File: gs://la-traffic-collision/traffic-collision-data-from-2010-to-present.csv
[2025-04-09T22:45:43.037+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-09T22:45:43.038+0000] {logging_mixin.py:190} INFO - Task start:2025-04-09 22:45:28.427689+00:00 end:2025-04-09 22:45:43.035993+00:00 duration:14.608304
[2025-04-09T22:45:43.039+0000] {logging_mixin.py:190} INFO - Task:<Task(GCSToBigQueryOperator): load_csv_to_bigquery> dag:<DAG: la_traffic_download_to_bq_via_url> dagrun:<DagRun la_traffic_download_to_bq_via_url @ 2025-04-08 00:00:00+00:00: scheduled__2025-04-08T00:00:00+00:00, state:running, queued_at: 2025-04-09 22:43:54.599707+00:00. externally triggered: False>
[2025-04-09T22:45:43.039+0000] {logging_mixin.py:190} INFO - Failure caused by 400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 494907; errors: 1; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 494907; errors: 1; max bad: 0; error percent: 0; reason: invalid, location: gs://la-traffic-collision/traffic-collision-data-from-2010-to-present.csv, message: Error while reading data, error message: Bad character (ASCII 0) encountered.; line_number: 137460 byte_offset_to_start_of_line: 52492230 column_index: 0 column_name: "dr_number" column_type: INT64 value: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000..." File: gs://la-traffic-collision/traffic-collision-data-from-2010-to-present.csv
[2025-04-09T22:45:43.040+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=la_traffic_download_to_bq_via_url, task_id=load_csv_to_bigquery, run_id=scheduled__2025-04-08T00:00:00+00:00, execution_date=20250408T000000, start_date=20250409T224528, end_date=20250409T224543
[2025-04-09T22:45:43.072+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-09T22:45:43.073+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 49 for task load_csv_to_bigquery (400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 494907; errors: 1; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 494907; errors: 1; max bad: 0; error percent: 0; reason: invalid, location: gs://la-traffic-collision/traffic-collision-data-from-2010-to-present.csv, message: Error while reading data, error message: Bad character (ASCII 0) encountered.; line_number: 137460 byte_offset_to_start_of_line: 52492230 column_index: 0 column_name: "dr_number" column_type: INT64 value: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000..." File: gs://la-traffic-collision/traffic-collision-data-from-2010-to-present.csv; 103)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 458, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 494907; errors: 1; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 494907; errors: 1; max bad: 0; error percent: 0; reason: invalid, location: gs://la-traffic-collision/traffic-collision-data-from-2010-to-present.csv, message: Error while reading data, error message: Bad character (ASCII 0) encountered.; line_number: 137460 byte_offset_to_start_of_line: 52492230 column_index: 0 column_name: "dr_number" column_type: INT64 value: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000..." File: gs://la-traffic-collision/traffic-collision-data-from-2010-to-present.csv
[2025-04-09T22:45:43.123+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-09T22:45:43.137+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T22:45:43.139+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
