[2025-04-06T01:39:32.245+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-06T01:39:32.253+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: la_traffic_download_to_bq_via_url.unzip_file scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-06T01:39:32.256+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: la_traffic_download_to_bq_via_url.unzip_file scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-06T01:39:32.256+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-06T01:39:32.261+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): unzip_file> on 2025-04-05 00:00:00+00:00
[2025-04-06T01:39:32.264+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=202) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-06T01:39:32.265+0000] {standard_task_runner.py:72} INFO - Started process 204 to run task
[2025-04-06T01:39:32.266+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'la_traffic_download_to_bq_via_url', 'unzip_file', 'scheduled__2025-04-05T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpg_mi1sye']
[2025-04-06T01:39:32.266+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask unzip_file
[2025-04-06T01:39:32.286+0000] {task_command.py:467} INFO - Running <TaskInstance: la_traffic_download_to_bq_via_url.unzip_file scheduled__2025-04-05T00:00:00+00:00 [running]> on host 78a2e318ec3f
[2025-04-06T01:39:32.316+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='la_traffic_download_to_bq_via_url' AIRFLOW_CTX_TASK_ID='unzip_file' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T00:00:00+00:00'
[2025-04-06T01:39:32.318+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-06T01:39:32.318+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-06T01:39:32.318+0000] {logging_mixin.py:190} INFO - Current task name:unzip_file state:running start_date:2025-04-06 01:39:32.253503+00:00
[2025-04-06T01:39:32.318+0000] {logging_mixin.py:190} INFO - Dag name:la_traffic_download_to_bq_via_url and current dag run status:running
[2025-04-06T01:39:32.318+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-06T01:39:32.710+0000] {logging_mixin.py:190} INFO - Extracted: ['socrata_metadata.json', 'traffic-collision-data-from-2010-to-present.csv']
[2025-04-06T01:39:32.713+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 54, in unzip_file
    raise Exception("Expected CSV not found in the ZIP.")
Exception: Expected CSV not found in the ZIP.
[2025-04-06T01:39:32.738+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-06T01:39:32.740+0000] {logging_mixin.py:190} INFO - Task start:2025-04-06 01:39:32.253503+00:00 end:2025-04-06 01:39:32.737131+00:00 duration:0.483628
[2025-04-06T01:39:32.741+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): unzip_file> dag:<DAG: la_traffic_download_to_bq_via_url> dagrun:<DagRun la_traffic_download_to_bq_via_url @ 2025-04-05 00:00:00+00:00: scheduled__2025-04-05T00:00:00+00:00, state:running, queued_at: 2025-04-06 01:39:25.789269+00:00. externally triggered: False>
[2025-04-06T01:39:32.741+0000] {logging_mixin.py:190} INFO - Failure caused by Expected CSV not found in the ZIP.
[2025-04-06T01:39:32.742+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=la_traffic_download_to_bq_via_url, task_id=unzip_file, run_id=scheduled__2025-04-05T00:00:00+00:00, execution_date=20250405T000000, start_date=20250406T013932, end_date=20250406T013932
[2025-04-06T01:39:32.762+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-06T01:39:32.763+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task unzip_file (Expected CSV not found in the ZIP.; 204)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 54, in unzip_file
    raise Exception("Expected CSV not found in the ZIP.")
Exception: Expected CSV not found in the ZIP.
[2025-04-06T01:39:32.798+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-06T01:39:32.810+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-06T01:39:32.811+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
